services:
  backend:
    build:
      context: ../baceknd
      dockerfile: dockerfile
    container_name: backend
    image: lagartin1/devops-ci-cd-taller:api-latest
    ports:
      - "3000:3000"
    env_file:
      - ../baceknd/.env
    environment:
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      PORT: 3000
  
  frontend:
    build:
      context: ../frontend
      dockerfile: dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api}
    image: lagartin1/devops-ci-cd-taller:frontend-latest
    container_name: frontend
    ports:
      - "5173:80"
