FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npm run prisma:generate

COPY src ./src
COPY server.ts tsconfig.json ./

ENV NODE_ENV=production
EXPOSE 3000

CMD ["npm", "start"]
